# Название вашего сайта
title: Домашний университет

# Email для связи (необязательно)
email: ваш_email@example.com

# Описание сайта
description: База знаний для личного развития и обучения.

# Тема Jekyll (используем Minima, простую и популярную тему)
theme: minima

# URL вашего сайта (если хотите использовать кастомный домен, добавьте его здесь)
url: https://ваш_логин.github.io
baseurl: /

# Автор
author:
  name: Ваше имя
  bio: "Студент и любитель самообразования"
